### PR TITLE
Another way to workaround internal/export link conflict.

### PR DESCRIPTION
**Pull request by mtbakerguy**

### CODE REVIEW

**Comment by alphapapa** [comment]
Please check the line wrapping in the diff, and please provide some commentary or discussion outside of the diff.

**Comment by mtbakerguy** [comment]
Give people an easy way to avoid redundant TOCs in an exported document.

**Comment by alphapapa** [comment]
Again, please check the line wrapping.  The original source is not line-wrapped, so nor should the patch be.

And, again, please provide commentary in the commit message explaining the purpose of the change.  This PR, if its changes are necessary, should be a single commit that is as minimal and clean as possible.

Even better would be to describe the problem in a non-PR issue and then we could talk about potential solutions that may or may not include what is in this PR.

**Comment by alphapapa** [comment]
Links for documents rendered on GitHub should be fixed in v0.6, so I think this PR isn't needed anymore.  Closing.

**Pull request closed without merging**
